name: wallet_sdk
version: 0.0.1+1
homepage: https://github.com/fuseio/wallet_sdk
description: Fuse wallet core Dart library to interact with Ethereum based networks and APIs.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  http: ^0.13.3
  get_it: ^7.2.0
  web3dart: ^2.1.4
  dio: ^4.0.0
  injectable: ^1.4.1
dev_dependencies:
  build_runner: ^2.0.6
  injectable_generator: ^1.4.1
  http_mock_adapter: ^0.3.1
  mockito: ^5.0.10
  test: ^1.17.9
